config/routes.rb
Rails.application.routes.draw do
  root 'static#landing'
  devise_for :users
  resources :technologies
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/technology.rb
class Technology < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :technologies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
before_action :configure_permitted_parameters, if: :devise_controller?

protected

def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :occupation, :dob, :prof_pic])
  devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :occupation, :dob, :prof_pic])
end
end

app/controllers/comment_controller.rb
class CommentController < ApplicationController
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def landing
  end
end

app/controllers/technologies_controller.rb
class TechnologiesController < ApplicationController
  before_action :set_technology, only: [:show, :edit, :update, :destroy]

  # GET /technologies
  # GET /technologies.json
  def index
    @technologies = Technology.all
  end

  # GET /technologies/1
  # GET /technologies/1.json
  def show
  end

  # GET /technologies/new
  def new
    @technology = Technology.new
  end

  # GET /technologies/1/edit
  def edit
  end

  # POST /technologies
  # POST /technologies.json
  def create
    @technology = Technology.new(technology_params)

    respond_to do |format|
      if @technology.save
        format.html { redirect_to @technology, notice: 'Technology was successfully created.' }
        format.json { render :show, status: :created, location: @technology }
      else
        format.html { render :new }
        format.json { render json: @technology.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /technologies/1
  # PATCH/PUT /technologies/1.json
  def update
    respond_to do |format|
      if @technology.update(technology_params)
        format.html { redirect_to @technology, notice: 'Technology was successfully updated.' }
        format.json { render :show, status: :ok, location: @technology }
      else
        format.html { render :edit }
        format.json { render json: @technology.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /technologies/1
  # DELETE /technologies/1.json
  def destroy
    @technology.destroy
    respond_to do |format|
      format.html { redirect_to technologies_url, notice: 'Technology was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_technology
      @technology = Technology.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def technology_params
      params.require(:technology).permit(:technology, :date_created, :version, :desc, :logo, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/technologies_helper.rb
module TechnologiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMiniProjectHw</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'partials/nav' %>
    <%= yield %>
  </body>
</html>

app/views/partials/_nav.html.erb
<nav class="navbar navbar-expand-sm navbar-light bg-info">
  <%= link_to 'Home', root_path, class: 'navbar-brand' %>

  <ul class="navbar-nav mr-auto">
    <li class="nav-item">
      <%= link_to 'Technology', technologies_path, class:'nav-link' %>
    </li>
  </ul>

    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <a class="nav-link">User signed in as: <%= current_user.first_name %></a>
        </li>
        <li class="nav-item">
          <%= link_to 'Edit Profile', edit_user_registration_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item active">
          <%= link_to 'Login', new_user_session_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
</nav>

app/views/technologies/_form.html.erb
<div class="container">
<%= form_with(model: technology, local: true) do |form| %>
  <% if technology.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(technology.errors.count, "error") %> prohibited this technology from being saved:</h2>

      <ul>
      <% technology.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :technology %>
    <%= form.text_field :technology , class: 'form-control'%>
  </div>

  <div class="form-group">
    <%= form.label :date_created %>
    <%= form.date_select :date_created , class: 'form-control'%>
  </div>

  <div class="form-group">
    <%= form.label :version %>
    <%= form.number_field :version , class: 'form-control'%>
  </div>

  <div class="form-group">
    <%= form.label :desc %>
    <%= form.text_area :desc , class: 'form-control'%>
  </div>

  <div class="form-group">
    <%= form.label :logo %>
    <%= form.text_field :logo , class: 'form-control'%>
  </div>

  <div class="form-group">
    <%= form.label :user_id %>
    <%= form.number_field :user_id , class: 'form-control'%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/technologies/edit.html.erb
<h1>Editing Technology</h1>

<%= render 'form', technology: @technology %>

<%= link_to 'Show', @technology , class: 'btn btn-info'%> |
<%= link_to 'Back', technologies_path , class: 'btn btn-info'%>

app/views/technologies/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<h1>Technologies</h1>

<table class="table">
  <thead>
    <tr>
      <th>Technology</th>
      <th>Date created</th>
      <th>Version</th>
      <th>Desc</th>
      <th>Logo</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @technologies.each do |tech| %>
      <tr>
        <td><%= tech.technology %></td>
        <td><%= tech.date_created %></td>
        <td><%= tech.version %></td>
        <td><%= tech.desc %></td>
        <td><%= tech.logo %></td>
        <td><%= tech.user.first_name %></td>
        <td><%= link_to 'Show', tech , class: 'btn btn-info'%></td>
        <td><%= link_to 'Edit', edit_technology_path(tech) , class: 'btn btn-info'%></td>
        <td><%= link_to 'Destroy', tech, method: :delete, data: { confirm: 'Are you sure?' } , class: 'btn btn-info'%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Tech', new_technology_path %>
</div>

app/views/technologies/new.html.erb
<h1>New Technology</h1>

<%= render 'form', technology: @technology %>

<%= link_to 'Back', technologies_path , class: 'btn btn-info'%>

app/views/technologies/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>



<p>
  <strong>Technology:</strong>
  <%= @technology.technology %>
</p>

<p>
  <strong>Date created:</strong>
  <%= @technology.date_created %>
</p>

<p>
  <strong>Version:</strong>
  <%= @technology.version %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @technology.desc %>
</p>

<p>
  <strong>Logo:</strong>
  <%= @technology.logo %>
</p>

<p>
  <strong>User:</strong>
  <%= @technology.user_id %>
</p>

<%= link_to 'Edit', edit_technology_path(@technology), class: 'btn btn-info' %> |
<%= link_to 'Back', technologies_path , class: 'btn btn-info'%>

</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>